### ISSUE TITLE
Day 4 - How on earth is this so fast?

### ISSUE THREAD

**Issue by omerbenamram** [matklad/aoc2019#1]
Hi @matklad!

Thanks for posting those solutions online!
I was solving day4 and was playing around with optimizations, mostly related to allocations and algorithmic improvements.
The best I got was around 1ms - https://github.com/omerbenamram/AOC2019/blob/master/day4/src/lib.rs, from here I couldn't get anything else to squeeze using perf, the flamegraphs would just show the functions.

I saw that you had an "inlined" version, and I was blown away by the fact it clocks in around 17us, almost two orders of magnitude faster than the best I could get.

If you could explain what is going here - or what is the reasoning that made you take this approach it would be very appreciated :)
https://github.com/matklad/aoc2019/blob/9806c133db7a3e7a286138fb6a3122eb755d3d59/src/bin/day4.rs#L54

**Comment by matklad** [comment]
The main trick is picking a more asymptotically optimal algorithm: I think in your solution you try all numbers in `lo ..= hi`. My solutions specifically looks only at the numbers with increasing sequence of digits (and there are far fewer "monotone" numbers than all numbers).

My specific way to check only increasing numbers is probably both ugly and slow. Like, the stupidest thing to write would be smth like this:

```rust
for digit_1 in 0..=9 {
  for digit_2 in d1 ..= 9 {
    for digit_3 in d2 ..= 9 {
        ...
    }
  }
}
```

recursive functions/macros are just a way to generalize this pattern to arbitrary depth. Perhaps a more elegant way to do this is to implement "+1" operation on monotone numbers and then just call it in the loop. 

From the implementation POV, the interesting bit is that macro_based solution is consistently faster than a recursive one, although in theory LLVM should be able to inline everything equialently.

**Comment by matklad** [comment]
Ok, you've nerd-sniped me, lets see how a ` + 1` version fares...

**Comment by matklad** [comment]
Pushed increment version: https://github.com/matklad/aoc2019/commit/685cc5d0f2f583173cf5bf317491d4e9ca294cea

It's **massively** simpler to write, but perf-wise macro-based solution is still a perf champ!

```
22:36:23|~/projects/aoc|master⚡*
λ hyperfine './target/release/day4 2' './target/release/day4 3' './target/release/day4 4'
Benchmark #1: ./target/release/day4 2
  Time (mean ± σ):      17.0 ms ±   1.5 ms    [User: 16.8 ms, System: 0.4 ms]
  Range (min … max):    14.9 ms …  25.4 ms    104 runs
 
  Warning: The first benchmarking run for this command was significantly slower than the rest (25.4 ms). This could be caused by (filesystem) caches that were not filled until after the first run. You should consider using the '--warmup' option to fill those caches before the actual benchmark. Alternatively, use the '--prepare' option to clear the caches before each timing run.
 
Benchmark #2: ./target/release/day4 3
  Time (mean ± σ):      11.5 ms ±   0.8 ms    [User: 11.4 ms, System: 0.3 ms]
  Range (min … max):     9.9 ms …  13.3 ms    199 runs
 
Benchmark #3: ./target/release/day4 4
  Time (mean ± σ):      14.2 ms ±   1.2 ms    [User: 13.9 ms, System: 0.5 ms]
  Range (min … max):    12.5 ms …  18.0 ms    145 runs
 
Summary
  './target/release/day4 3' ran
    1.23 ± 0.13 times faster than './target/release/day4 4'
    1.47 ± 0.17 times faster than './target/release/day4 2'
```

EDIT: don't look at the absolute numbers here, code is run many times to try make measurements meaningful. They still might be meaningless, as I am not sure that the compiler doesn't hoist computations out of the loop, but, on the first blush, the results look reasonable.

**Comment by omerbenamram** [comment]
@matklad My solution was indeed an "optimal" brute force.

The `increment` version makes perfect sense, it's also much easier to reason about than the macro ones. I was mislead to think there is some inlining voodoo going on that is yielding the performance boost, where it was just a smart optimization of the problem space.
This is very neat - I like it 😄 thanks again for the explanation!
